//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.23 at 10:56:51 PM CEST 
//


package de.radiohacks.frinmean.model;

import org.simpleframework.xml.Default;
import org.simpleframework.xml.DefaultType;
import org.simpleframework.xml.Element;
import org.simpleframework.xml.Root;

@Default(DefaultType.FIELD)
@Root(name = "LocationMessage", strict = false)
public class LocationMessage {

    @Element(name = "Lat", required = true)
    protected String lat;
    @Element(name = "Lon", required = true)
    protected String lon;

    public String getLat() {
        return lat;
    }

    public void setLat(String value) {
        this.lat = value;
    }

    public String getLon() {
        return lon;
    }

    public void setLon(String value) {
        this.lon = value;
    }

}

