//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.23 at 10:56:51 PM CEST 
//


package de.radiohacks.frinmean.model;

import org.simpleframework.xml.Default;
import org.simpleframework.xml.DefaultType;
import org.simpleframework.xml.Element;
import org.simpleframework.xml.Root;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MessageID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="MessageTyp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SendTimestamp" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="ReadTimestamp" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="OwningUser">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="OwningUserName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="OwningUserID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TextMsgID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ImageMsgID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ContactMsgID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="LocationMsgID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="FileMsgID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@Default(DefaultType.FIELD)
@Root(name = "Message", strict = false)
public class Message {

    @Element(name = "MessageID", required = false)
    protected int messageID;
    @Element(name = "MessageTyp", required = false)
    protected String messageTyp;
    @Element(required = false, name = "SendTimestamp")
    protected long sendTimestamp;
    @Element(required = false, name = "ReadTimestamp")
    protected long readTimestamp;
    @Element(required = false, name = "ShowTimestamp")
    protected long showTimestamp;
    @Element(name = "OwningUser", required = false)
    protected OwningUser owningUser;
    @Element(required = false, name = "TextMsgID")
    protected int textMsgID;
    @Element(required = false, name = "ImageMsgID")
    protected int imageMsgID;
    @Element(required = false, name = "ContactMsgID")
    protected int contactMsgID;
    @Element(required = false, name = "LocationMsgID")
    protected int locationMsgID;
    @Element(required = false, name = "FileMsgID")
    protected int fileMsgID;
    @Element(required = false, name = "VideoMsgID")
    protected int videoMsgID;
    @Element(required = false, name = "OriginMsgID")
    protected int originMsgID;
    @Element(required = false, name = "NumberTotal")
    protected int numberTotal;
    @Element(required = false, name = "NumberRead")
    protected int numberRead;
    @Element(required = false, name = "NumberShow")
    protected int numberShow;

    public int getMessageID() {
        return messageID;
    }

    public void setMessageID(int value) {
        this.messageID = value;
    }

    public String getMessageTyp() {
        return messageTyp;
    }

    public void setMessageTyp(String value) {
        this.messageTyp = value;
    }

    public long getSendTimestamp() {
        return sendTimestamp;
    }

    public void setSendTimestamp(long value) {
        this.sendTimestamp = value;
    }

    public long getReadTimestamp() {
        return readTimestamp;
    }

    public void setReadTimestamp(long value) {
        this.readTimestamp = value;
    }

    public long getShowTimestamp() {
        return showTimestamp;
    }

    public void setShowTimestamp(long value) {
        this.showTimestamp = value;
    }

    public OwningUser getOwningUser() {
        return owningUser;
    }

    public void setOwningUser(OwningUser value) {
        this.owningUser = value;
    }

    public int getTextMsgID() {
        return textMsgID;
    }

    public void setTextMsgID(int value) {
        this.textMsgID = value;
    }

    public int getImageMsgID() {
        return imageMsgID;
    }

    public void setImageMsgID(int value) {
        this.imageMsgID = value;
    }

    public int getContactMsgID() {
        return contactMsgID;
    }

    public void setContactMsgID(int value) {
        this.contactMsgID = value;
    }

    public int getLocationMsgID() {
        return locationMsgID;
    }

    public void setLocationMsgID(int value) {
        this.locationMsgID = value;
    }

    public int getFileMsgID() {
        return fileMsgID;
    }

    public void setFileMsgID(int value) {
        this.fileMsgID = value;
    }

    public int getVideoMsgID() {
        return videoMsgID;
    }

    public void setVideoMsgID(int value) {
        this.videoMsgID = value;
    }

    public int getOriginMsgID() {
        return originMsgID;
    }

    public void setOriginMsgID(int value) {
        this.originMsgID = value;
    }

    public int getNumberTotal() {
        return numberTotal;
    }

    public void setNumberTotal(int value) {
        this.numberTotal = value;
    }

    public int getNumberRead() {
        return numberRead;
    }

    public void setNumberRead(int value) {
        this.numberRead = value;
    }

    public int getNumberShow() {
        return numberShow;
    }

    public void setNumberShow(int value) {
        this.numberShow = value;
    }
}