//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.23 at 10:56:51 PM CEST 
//


package de.radiohacks.frinmean.model;

import org.simpleframework.xml.Default;
import org.simpleframework.xml.DefaultType;
import org.simpleframework.xml.Element;
import org.simpleframework.xml.ElementList;
import org.simpleframework.xml.Root;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element name="Message" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="MessageID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                     &lt;element name="MessageTyp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="SendTimestamp" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                     &lt;element name="ReadTimestamp" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                     &lt;element name="OwningUser">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="OwningUserName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                               &lt;element name="OwningUserID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="TextMsgID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                     &lt;element name="ImageMsgID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                     &lt;element name="ContactMsgID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                     &lt;element name="LocationMsgID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                     &lt;element name="FileMsgID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/sequence>
 *         &lt;element name="Errortext" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@Default(DefaultType.FIELD)
@Root(name = "OutFetchMessageFromChat", strict = false)
public class OutFetchMessageFromChat {

    @ElementList(required = false, inline = true, name = "Message")
    protected List<Message> message;
    @Element(required = false, name = "Errortext")
    protected String errortext;

    public List<Message> getMessage() {
        if (message == null) {
            message = new ArrayList<Message>();
        }
        return this.message;
    }

    public String getErrortext() {
        return errortext;
    }

    public void setErrortext(String value) {
        this.errortext = value;
    }
}
