//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.14 at 08:27:05 PM CET 
//


package de.radiohacks.frinmean.model;

import org.simpleframework.xml.Default;
import org.simpleframework.xml.DefaultType;
import org.simpleframework.xml.Element;
import org.simpleframework.xml.Root;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element name="VideoMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="VideoSize" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;/sequence>
 *         &lt;element name="Errortext" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@Default(DefaultType.FIELD)
@Root(name = "OutGetVideoMessageMetaData")
public class OutGetVideoMessageMetaData {

    @Element(required = false, name = "VideoMessage")
    protected String videoMessage;
    @Element(required = false, name = "VideoSize")
    protected Long videoSize;
    @Element(required = false, name = "Errortext")
    protected String errortext;

    /**
     * Gets the value of the videoMessage property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVideoMessage() {
        return videoMessage;
    }

    /**
     * Sets the value of the videoMessage property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVideoMessage(String value) {
        this.videoMessage = value;
    }

    /**
     * Gets the value of the videoSize property.
     *
     * @return possible object is
     * {@link Long }
     */
    public Long getVideoSize() {
        return videoSize;
    }

    /**
     * Sets the value of the videoSize property.
     *
     * @param value allowed object is
     *              {@link Long }
     */
    public void setVideoSize(Long value) {
        this.videoSize = value;
    }

    /**
     * Gets the value of the errortext property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getErrortext() {
        return errortext;
    }

    /**
     * Sets the value of the errortext property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setErrortext(String value) {
        this.errortext = value;
    }

}
