//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.23 at 10:56:51 PM CEST 
//


package de.radiohacks.frinmean.model;

import org.simpleframework.xml.Default;
import org.simpleframework.xml.DefaultType;
import org.simpleframework.xml.Element;
import org.simpleframework.xml.Root;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element name="Username" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="UserID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *           &lt;element name="SignUp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="Reason" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;/sequence>
 *         &lt;element name="Errortext" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@Default(DefaultType.FIELD)
@Root(name = "OutSignUp", strict = false)
public class OutSignUp {

    @Element(required = false, name = "Username")
    protected String username;
    @Element(required = false, name = "UserID")
    protected Integer userID;
    @Element(required = false, name = "SignUp")
    protected String signUp;
    @Element(required = false, name = "Reason")
    protected String reason;
    @Element(required = false, name = "Errortext")
    protected String errortext;

    /**
     * Gets the value of the username property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUsername(String value) {
        this.username = value;
    }

    /**
     * Gets the value of the userID property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getUserID() {
        return userID;
    }

    /**
     * Sets the value of the userID property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setUserID(Integer value) {
        this.userID = value;
    }

    /**
     * Gets the value of the signUp property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSignUp() {
        return signUp;
    }

    /**
     * Sets the value of the signUp property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSignUp(String value) {
        this.signUp = value;
    }

    /**
     * Gets the value of the reason property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getReason() {
        return reason;
    }

    /**
     * Sets the value of the reason property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setReason(String value) {
        this.reason = value;
    }

    /**
     * Gets the value of the errortext property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getErrortext() {
        return errortext;
    }

    /**
     * Sets the value of the errortext property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setErrortext(String value) {
        this.errortext = value;
    }

}
