//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.16 at 10:37:05 PM CET 
//


package de.radiohacks.frinmean.model;

import org.simpleframework.xml.Default;
import org.simpleframework.xml.DefaultType;
import org.simpleframework.xml.Element;
import org.simpleframework.xml.Root;

/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element name="ImageID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *           &lt;element name="ImageFileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;/sequence>
 *         &lt;element name="Errortext" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@Default(DefaultType.FIELD)
@Root(name = "OutSendImageMessage", strict = false)
public class OutSendImageMessage {

    @Element(required = false, name = "ImageID")
    protected Integer imageID;
    @Element(required = false, name = "ImageFileName")
    protected String imageFileName;
    @Element(required = false, name = "Errortext")
    protected String errortext;

    /**
     * Gets the value of the imageID property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getImageID() {
        return imageID;
    }

    /**
     * Sets the value of the imageID property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setImageID(Integer value) {
        this.imageID = value;
    }

    /**
     * Gets the value of the imageFileName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getImageFileName() {
        return imageFileName;
    }

    /**
     * Sets the value of the imageFileName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setImageFileName(String value) {
        this.imageFileName = value;
    }

    /**
     * Gets the value of the errortext property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getErrortext() {
        return errortext;
    }

    /**
     * Sets the value of the errortext property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setErrortext(String value) {
        this.errortext = value;
    }

}
