//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.23 at 10:56:51 PM CEST 
//


package de.radiohacks.frinmean.model;

import org.simpleframework.xml.Default;
import org.simpleframework.xml.DefaultType;
import org.simpleframework.xml.Element;

/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OwningUserName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OwningUserID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@Default(DefaultType.FIELD)
public class OwningUser {

    @Element(name = "OwningUserName", required = true)
    protected String owningUserName;
    @Element(required = false, name = "OwningUserID")
    protected int owningUserID;

    public String getOwningUserName() {
        return owningUserName;
    }

    public void setOwningUserName(String value) {
        this.owningUserName = value;
    }

    public int getOwningUserID() {
        return owningUserID;
    }

    public void setOwningUserID(int value) {
        this.owningUserID = value;
    }

}

