//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.02 at 09:24:09 PM CET 
//


package de.radiohacks.frinmean.modelshort;

import org.simpleframework.xml.Element;
import org.simpleframework.xml.Root;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PW" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="MID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="MT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */

@Root(name = "IIMIC", strict = false)
public class IIMIC {

    @Element(name = "UN", required = true)
    protected String un;
    @Element(name = "PW", required = true)
    protected String pw;
    @Element(required = false, name = "CID")
    protected int cid;
    @Element(required = false, name = "MID")
    protected int mid;
    @Element(name = "MT", required = true)
    protected String mt;

    /**
     * Gets the value of the un property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getUN() {
        return un;
    }

    /**
     * Sets the value of the un property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUN(String value) {
        this.un = value;
    }

    /**
     * Gets the value of the pw property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPW() {
        return pw;
    }

    /**
     * Sets the value of the pw property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPW(String value) {
        this.pw = value;
    }

    /**
     * Gets the value of the cid property.
     */
    public int getCID() {
        return cid;
    }

    /**
     * Sets the value of the cid property.
     */
    public void setCID(int value) {
        this.cid = value;
    }

    /**
     * Gets the value of the mid property.
     */
    public int getMID() {
        return mid;
    }

    /**
     * Sets the value of the mid property.
     */
    public void setMID(int value) {
        this.mid = value;
    }

    /**
     * Gets the value of the mt property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMT() {
        return mt;
    }

    /**
     * Sets the value of the mt property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMT(String value) {
        this.mt = value;
    }

}
