//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.26 at 08:36:09 PM CET 
//


package de.radiohacks.frinmean.modelshort;

import org.simpleframework.xml.Default;
import org.simpleframework.xml.DefaultType;
import org.simpleframework.xml.Element;
import org.simpleframework.xml.Root;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IcM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IcMD5" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@Default(DefaultType.FIELD)
@Root(name = "ISIcM", strict = false)
public class ISIcM {

    @Element(name = "IcM", required = true)
    protected String icM;
    @Element(name = "IcMD5", required = true)
    protected String icMD5;

    /**
     * Gets the value of the icM property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIcM() {
        return icM;
    }

    /**
     * Sets the value of the icM property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIcM(String value) {
        this.icM = value;
    }

    /**
     * Gets the value of the icMD5 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIcMD5() {
        return icMD5;
    }

    /**
     * Sets the value of the icMD5 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIcMD5(String value) {
        this.icMD5 = value;
    }

}
