/**
 * Copyright � 2015, Thomas Schreiner, thomas1.schreiner@googlemail.com
 * All rights reserved.
 * <p/>
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * <p/>
 * 1. Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 * <p/>
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * <p/>
 * The views and conclusions contained in the software and documentation are those
 * of the authors and should not be interpreted as representing official policies,
 * either expressed or implied, of the FreeBSD Project.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.05 at 09:19:06 PM CET 
//


package de.radiohacks.frinmean.modelshort;

import org.simpleframework.xml.Element;
import org.simpleframework.xml.Root;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="MT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SdT" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="RdT" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="ShT" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element ref="{}OU"/>
 *         &lt;element name="TMID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="IMID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="CMID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="LMID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="FMID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="VMID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="OMID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@Root(name = "M", strict=false)
public class M {

    @Element(required = false, name = "MID")
    protected int mid;
    @Element(name = "MT", required = true)
    protected String mt;
    @Element(required = false, name = "SdT")
    protected long sdT;
    @Element(required = false, name = "RdT")
    protected long rdT;
    @Element(required = false, name = "ShT")
    protected long shT;
    @Element(name = "OU", required = true)
    protected OU ou;
    @Element(required = false, name = "TMID")
    protected int tmid;
    @Element(required = false, name = "IMID")
    protected int imid;
    @Element(required = false, name = "CMID")
    protected int cmid;
    @Element(required = false, name = "LMID")
    protected int lmid;
    @Element(required = false, name = "FMID")
    protected int fmid;
    @Element(required = false, name = "VMID")
    protected int vmid;
    @Element(required = false, name = "OMID")
    protected int omid;

    /**
     * Gets the value of the mid property.
     * 
     */
    public int getMID() {
        return mid;
    }

    /**
     * Sets the value of the mid property.
     * 
     */
    public void setMID(int value) {
        this.mid = value;
    }

    /**
     * Gets the value of the mt property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMT() {
        return mt;
    }

    /**
     * Sets the value of the mt property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMT(String value) {
        this.mt = value;
    }

    /**
     * Gets the value of the sdT property.
     * 
     */
    public long getSdT() {
        return sdT;
    }

    /**
     * Sets the value of the sdT property.
     * 
     */
    public void setSdT(long value) {
        this.sdT = value;
    }

    /**
     * Gets the value of the rdT property.
     * 
     */
    public long getRdT() {
        return rdT;
    }

    /**
     * Sets the value of the rdT property.
     * 
     */
    public void setRdT(long value) {
        this.rdT = value;
    }

    /**
     * Gets the value of the shT property.
     * 
     */
    public long getShT() {
        return shT;
    }

    /**
     * Sets the value of the shT property.
     * 
     */
    public void setShT(long value) {
        this.shT = value;
    }

    /**
     * Gets the value of the ou property.
     *
     * @return
     *     possible object is
     *     {@link OU }
     *     
     */
    public OU getOU() {
        return ou;
    }

    /**
     * Sets the value of the ou property.
     *
     * @param value
     *     allowed object is
     *     {@link OU }
     *     
     */
    public void setOU(OU value) {
        this.ou = value;
    }

    /**
     * Gets the value of the tmid property.
     * 
     */
    public int getTMID() {
        return tmid;
    }

    /**
     * Sets the value of the tmid property.
     * 
     */
    public void setTMID(int value) {
        this.tmid = value;
    }

    /**
     * Gets the value of the imid property.
     * 
     */
    public int getIMID() {
        return imid;
    }

    /**
     * Sets the value of the imid property.
     * 
     */
    public void setIMID(int value) {
        this.imid = value;
    }

    /**
     * Gets the value of the cmid property.
     * 
     */
    public int getCMID() {
        return cmid;
    }

    /**
     * Sets the value of the cmid property.
     * 
     */
    public void setCMID(int value) {
        this.cmid = value;
    }

    /**
     * Gets the value of the lmid property.
     * 
     */
    public int getLMID() {
        return lmid;
    }

    /**
     * Sets the value of the lmid property.
     * 
     */
    public void setLMID(int value) {
        this.lmid = value;
    }

    /**
     * Gets the value of the fmid property.
     * 
     */
    public int getFMID() {
        return fmid;
    }

    /**
     * Sets the value of the fmid property.
     * 
     */
    public void setFMID(int value) {
        this.fmid = value;
    }

    /**
     * Gets the value of the vmid property.
     * 
     */
    public int getVMID() {
        return vmid;
    }

    /**
     * Sets the value of the vmid property.
     * 
     */
    public void setVMID(int value) {
        this.vmid = value;
    }

    /**
     * Gets the value of the omid property.
     * 
     */
    public int getOMID() {
        return omid;
    }

    /**
     * Sets the value of the omid property.
     * 
     */
    public void setOMID(int value) {
        this.omid = value;
    }

}
