//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.26 at 08:36:09 PM CET 
//


package de.radiohacks.frinmean.modelshort;

import org.simpleframework.xml.Default;
import org.simpleframework.xml.DefaultType;
import org.simpleframework.xml.Element;
import org.simpleframework.xml.Root;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="MT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SdT" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="RdT" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="ShT" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element ref="{}OU"/>
 *         &lt;element name="TMID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="IMID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="CMID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="LMID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="FMID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="VMID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="OMID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@Default(DefaultType.FIELD)
@Root(name = "M", strict = false)
public class M {

    @Element(required = false, name = "MID")
    protected int mid;
    @Element(name = "MT", required = true)
    protected String mt;
    @Element(required = false, name = "SdT")
    protected long sdT;
    @Element(required = false, name = "RdT")
    protected long rdT;
    @Element(required = false, name = "ShT")
    protected long shT;
    @Element(name = "OU", required = true)
    protected OU ou;
    @Element(required = false, name = "TMID")
    protected int tmid;
    @Element(required = false, name = "IMID")
    protected int imid;
    @Element(required = false, name = "CMID")
    protected int cmid;
    @Element(required = false, name = "LMID")
    protected int lmid;
    @Element(required = false, name = "FMID")
    protected int fmid;
    @Element(required = false, name = "VMID")
    protected int vmid;
    @Element(required = false, name = "OMID")
    protected int omid;

    /**
     * Gets the value of the mid property.
     */
    public int getMID() {
        return mid;
    }

    /**
     * Sets the value of the mid property.
     */
    public void setMID(int value) {
        this.mid = value;
    }

    /**
     * Gets the value of the mt property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMT() {
        return mt;
    }

    /**
     * Sets the value of the mt property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMT(String value) {
        this.mt = value;
    }

    /**
     * Gets the value of the sdT property.
     */
    public long getSdT() {
        return sdT;
    }

    /**
     * Sets the value of the sdT property.
     */
    public void setSdT(long value) {
        this.sdT = value;
    }

    /**
     * Gets the value of the rdT property.
     */
    public long getRdT() {
        return rdT;
    }

    /**
     * Sets the value of the rdT property.
     */
    public void setRdT(long value) {
        this.rdT = value;
    }

    /**
     * Gets the value of the shT property.
     */
    public long getShT() {
        return shT;
    }

    /**
     * Sets the value of the shT property.
     */
    public void setShT(long value) {
        this.shT = value;
    }

    /**
     * Gets the value of the ou property.
     *
     * @return possible object is
     * {@link OU }
     */
    public OU getOU() {
        return ou;
    }

    /**
     * Sets the value of the ou property.
     *
     * @param value allowed object is
     *              {@link OU }
     */
    public void setOU(OU value) {
        this.ou = value;
    }

    /**
     * Gets the value of the tmid property.
     */
    public int getTMID() {
        return tmid;
    }

    /**
     * Sets the value of the tmid property.
     */
    public void setTMID(int value) {
        this.tmid = value;
    }

    /**
     * Gets the value of the imid property.
     */
    public int getIMID() {
        return imid;
    }

    /**
     * Sets the value of the imid property.
     */
    public void setIMID(int value) {
        this.imid = value;
    }

    /**
     * Gets the value of the cmid property.
     */
    public int getCMID() {
        return cmid;
    }

    /**
     * Sets the value of the cmid property.
     */
    public void setCMID(int value) {
        this.cmid = value;
    }

    /**
     * Gets the value of the lmid property.
     */
    public int getLMID() {
        return lmid;
    }

    /**
     * Sets the value of the lmid property.
     */
    public void setLMID(int value) {
        this.lmid = value;
    }

    /**
     * Gets the value of the fmid property.
     */
    public int getFMID() {
        return fmid;
    }

    /**
     * Sets the value of the fmid property.
     */
    public void setFMID(int value) {
        this.fmid = value;
    }

    /**
     * Gets the value of the vmid property.
     */
    public int getVMID() {
        return vmid;
    }

    /**
     * Sets the value of the vmid property.
     */
    public void setVMID(int value) {
        this.vmid = value;
    }

    /**
     * Gets the value of the omid property.
     */
    public int getOMID() {
        return omid;
    }

    /**
     * Sets the value of the omid property.
     */
    public void setOMID(int value) {
        this.omid = value;
    }

}
