//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.26 at 08:36:09 PM CET 
//


package de.radiohacks.frinmean.modelshort;

import org.simpleframework.xml.Default;
import org.simpleframework.xml.DefaultType;
import org.simpleframework.xml.Element;
import org.simpleframework.xml.Root;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="UN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RD" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="SH" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@Default(DefaultType.FIELD)
@Root(name = "MI", strict = false)
public class MI {

    @Element(required = false, name = "UID")
    protected int uid;
    @Element(name = "UN", required = true)
    protected String un;
    @Element(required = false, name = "RD")
    protected long rd;
    @Element(required = false, name = "SH")
    protected long sh;

    /**
     * Gets the value of the uid property.
     */
    public int getUID() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     */
    public void setUID(int value) {
        this.uid = value;
    }

    /**
     * Gets the value of the un property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getUN() {
        return un;
    }

    /**
     * Sets the value of the un property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUN(String value) {
        this.un = value;
    }

    /**
     * Gets the value of the rd property.
     */
    public long getRD() {
        return rd;
    }

    /**
     * Sets the value of the rd property.
     */
    public void setRD(long value) {
        this.rd = value;
    }

    /**
     * Gets the value of the sh property.
     */
    public long getSH() {
        return sh;
    }

    /**
     * Sets the value of the sh property.
     */
    public void setSH(long value) {
        this.sh = value;
    }

}
