//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.02 at 09:26:35 PM CEST 
//


package de.radiohacks.frinmean.modelshort;

import org.simpleframework.xml.Default;
import org.simpleframework.xml.DefaultType;
import org.simpleframework.xml.Element;
import org.simpleframework.xml.Order;
import org.simpleframework.xml.Root;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element name="VM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="VS" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *           &lt;element name="VMD5" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;/sequence>
 *         &lt;element name="ET" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@Default(DefaultType.FIELD)
@Order(elements = {
        "vm",
        "vs",
        "vmd5",
        "et"
})
@Root(name = "OGViMMD", strict = false)
public class OGViMMD {

    @Element(required = false, name = "VM")
    protected String vm;
    @Element(required = false, name = "VS")
    protected Long vs;
    @Element(required = false, name = "VMD5")
    protected String vmd5;
    @Element(required = false, name = "ET")
    protected String et;

    /**
     * Gets the value of the vm property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVM() {
        return vm;
    }

    /**
     * Sets the value of the vm property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVM(String value) {
        this.vm = value;
    }

    /**
     * Gets the value of the vs property.
     *
     * @return possible object is
     * {@link Long }
     */
    public Long getVS() {
        return vs;
    }

    /**
     * Sets the value of the vs property.
     *
     * @param value allowed object is
     *              {@link Long }
     */
    public void setVS(Long value) {
        this.vs = value;
    }

    /**
     * Gets the value of the vmd5 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVMD5() {
        return vmd5;
    }

    /**
     * Sets the value of the vmd5 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVMD5(String value) {
        this.vmd5 = value;
    }

    /**
     * Gets the value of the et property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getET() {
        return et;
    }

    /**
     * Sets the value of the et property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setET(String value) {
        this.et = value;
    }

}
