//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.02 at 09:26:35 PM CEST 
//


package de.radiohacks.frinmean.modelshort;

import org.simpleframework.xml.Default;
import org.simpleframework.xml.DefaultType;
import org.simpleframework.xml.Element;
import org.simpleframework.xml.Order;
import org.simpleframework.xml.Root;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element name="Chat" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="CN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="CID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                     &lt;element ref="{}OU"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/sequence>
 *         &lt;element name="ET" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@Default(DefaultType.FIELD)
@Order(elements = {
        "chat",
        "et"
})
@Root(name = "OLiCh", strict = false)
public class OLiCh {

    @Element(required = false, name = "Chat")
    protected List<OLiCh.Chat> chat;
    @Element(required = false, name = "ET")
    protected String et;

    /**
     * Gets the value of the chat property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the chat property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChat().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link OLiCh.Chat }
     */
    public List<OLiCh.Chat> getChat() {
        if (chat == null) {
            chat = new ArrayList<OLiCh.Chat>();
        }
        return this.chat;
    }

    /**
     * Gets the value of the et property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getET() {
        return et;
    }

    /**
     * Sets the value of the et property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setET(String value) {
        this.et = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CN" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CID" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element ref="{}OU"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @Default(DefaultType.FIELD)
    public static class Chat {

        @Element(name = "CN", required = true)
        protected String cn;
        @Element(required = false, name = "CID")
        protected int cid;
        @Element(name = "OU", required = true)
        protected OU ou;

        /**
         * Gets the value of the cn property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getCN() {
            return cn;
        }

        /**
         * Sets the value of the cn property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setCN(String value) {
            this.cn = value;
        }

        /**
         * Gets the value of the cid property.
         */
        public int getCID() {
            return cid;
        }

        /**
         * Sets the value of the cid property.
         */
        public void setCID(int value) {
            this.cid = value;
        }

        /**
         * Gets the value of the ou property.
         *
         * @return possible object is
         * {@link OU }
         */
        public OU getOU() {
            return ou;
        }

        /**
         * Sets the value of the ou property.
         *
         * @param value allowed object is
         *              {@link OU }
         */
        public void setOU(OU value) {
            this.ou = value;
        }

    }

}
