//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.02 at 09:26:35 PM CEST 
//


package de.radiohacks.frinmean.modelshort;

import org.simpleframework.xml.Default;
import org.simpleframework.xml.DefaultType;
import org.simpleframework.xml.Element;
import org.simpleframework.xml.Root;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element name="UN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="UID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *           &lt;element name="SU" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="R" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;/sequence>
 *         &lt;element name="ET" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@Default(DefaultType.FIELD)
@Root(name = "OSiUp", strict = false)
public class OSiUp {

    @Element(required = false, name = "UN")
    protected String un;
    @Element(required = false, name = "UID")
    protected Integer uid;
    @Element(required = false, name = "SU")
    protected String su;
    @Element(required = false, name = "R")
    protected String r;
    @Element(required = false, name = "ET")
    protected String et;

    /**
     * Gets the value of the un property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getUN() {
        return un;
    }

    /**
     * Sets the value of the un property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUN(String value) {
        this.un = value;
    }

    /**
     * Gets the value of the uid property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getUID() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setUID(Integer value) {
        this.uid = value;
    }

    /**
     * Gets the value of the su property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSU() {
        return su;
    }

    /**
     * Sets the value of the su property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSU(String value) {
        this.su = value;
    }

    /**
     * Gets the value of the r property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getR() {
        return r;
    }

    /**
     * Sets the value of the r property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setR(String value) {
        this.r = value;
    }

    /**
     * Gets the value of the et property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getET() {
        return et;
    }

    /**
     * Sets the value of the et property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setET(String value) {
        this.et = value;
    }

}
